#!/usr/bin/env python3
"""
README Generator — takes folder analysis JSON and produces a structured README.md.
Tries Claude CLI first; falls back to rule-based generation if unavailable.
Preserves <!-- MANUAL SECTION START/END --> blocks.
"""
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

MANUAL_BLOCK_RE = re.compile(
    r"(<!-- MANUAL SECTION START -->.*?<!-- MANUAL SECTION END -->)",
    re.DOTALL,
)

README_TEMPLATE = """\
# 📁 {name}

## 🧠 Purpose
{purpose}

## ⚙️ Responsibilities
{responsibilities}

## 🔗 System Role
{system_role}

## 📂 Contents
{contents}

## 🔄 Dependencies
{dependencies}

## 🧩 Interactions
{interactions}

## 📈 Current Capabilities
{capabilities}

## ⚠️ Gaps & Weaknesses
{gaps}

## 🚀 Suggested Enhancements
{enhancements}

## 🔗 Connected Modules
{connected_modules}

## 📝 Change Log (Auto)
- {date}: README auto-generated by README Intelligence System
"""


def _extract_manual_blocks(content: str) -> list:
    return MANUAL_BLOCK_RE.findall(content)


def _restore_manual_blocks(new_content: str, manual_blocks: list) -> str:
    for block in manual_blocks:
        if block not in new_content:
            new_content += f"\n\n{block}\n"
    return new_content


def _extract_existing_changelog(content: str) -> list:
    """Preserve existing change log entries."""
    match = re.search(r"## 📝 Change Log.*?\n(.*?)(?=\n## |\Z)", content, re.DOTALL)
    if not match:
        return []
    lines = [l.strip() for l in match.group(1).splitlines() if l.strip().startswith("-")]
    return lines[:10]  # keep last 10


def _build_contents_section(analysis: dict) -> str:
    lines = []
    for f in analysis.get("files", []):
        lines.append(f"- `{f}`")
    for d in analysis.get("subdirectories", []):
        lines.append(f"- `{d}/` *(directory)*")
    return "\n".join(lines) if lines else "*(empty)*"


def _build_dependencies_section(analysis: dict) -> str:
    deps = analysis.get("workspace_references", [])
    if not deps:
        return "None detected"
    return "\n".join(f"- `{d}/`" for d in deps)


def _build_connected_modules(analysis: dict) -> str:
    refs = analysis.get("workspace_references", [])
    if not refs:
        return "*(no cross-organ references detected)*"
    lines = []
    for ref in refs:
        lines.append(f"- [`../{ref}/README.md`](../{ref}/README.md)")
    return "\n".join(lines)


def _build_capabilities_section(analysis: dict) -> str:
    caps = analysis.get("capabilities", [])
    if not caps:
        return "- Basic workspace component"
    return "\n".join(f"- {c}" for c in caps)


def _build_gaps_section(analysis: dict) -> str:
    gaps = analysis.get("gaps", [])
    if not gaps:
        return "None identified"
    return "\n".join(f"- {g}" for g in gaps)


def _build_responsibilities(analysis: dict) -> str:
    from hands.automation.readme.intelligence_engine import ORGAN_RESPONSIBILITIES
    organ = analysis.get("organ")
    if organ and organ in ORGAN_RESPONSIBILITIES:
        lines = ORGAN_RESPONSIBILITIES[organ]
    else:
        lines = []
        files = analysis.get("files", [])
        if any(f.endswith(".py") for f in files):
            lines.append("Python module execution")
        if any(f.endswith(".sh") for f in files):
            lines.append("Shell script automation")
        if any(f.endswith(".json") for f in files):
            lines.append("Configuration management")
        if not lines:
            lines = ["General workspace operations"]
    return "\n".join(f"- {r}" for r in lines)


def _build_enhancements(analysis: dict) -> str:
    suggestions = []
    gaps = analysis.get("gaps", [])
    if "No test coverage detected" in gaps:
        suggestions.append("Add unit and integration tests")
    if "Missing README.md" in gaps:
        suggestions.append("Document purpose and usage")
    organ = analysis.get("organ")
    if organ == "brain":
        suggestions.append("Add semantic clustering for memory retrieval")
    elif organ == "heart":
        suggestions.append("Add priority queuing with SLA tracking")
    elif organ == "eyes":
        suggestions.append("Add real-time alerting dashboard panels")
    elif organ == "lab":
        suggestions.append("Add A/B experiment comparison tracking")
    if not suggestions:
        suggestions = ["Add metrics collection", "Add integration tests"]
    return "\n".join(f"- {s}" for s in suggestions[:3])


def _rule_based_readme(analysis: dict, existing_content: str = "") -> str:
    manual_blocks = _extract_manual_blocks(existing_content)
    existing_changelog = _extract_existing_changelog(existing_content)

    organ = analysis.get("organ", "")
    system_role = (
        f"Part of the **{organ}** organ in the 12-organ SuneelWorkSpace architecture."
        if organ
        else "Supporting component within SuneelWorkSpace."
    )

    today = datetime.now().strftime("%Y-%m-%d")
    changelog_entries = [f"- {today}: README auto-updated by README Intelligence System"]
    for entry in existing_changelog:
        if today not in entry:
            changelog_entries.append(entry)

    readme = README_TEMPLATE.format(
        name=analysis.get("name", "Unknown"),
        purpose=analysis.get("purpose", "Workspace component"),
        responsibilities=_build_responsibilities(analysis),
        system_role=system_role,
        contents=_build_contents_section(analysis),
        dependencies=_build_dependencies_section(analysis),
        interactions="Emits `readme_updated` events to nervous system on change.",
        capabilities=_build_capabilities_section(analysis),
        gaps=_build_gaps_section(analysis),
        enhancements=_build_enhancements(analysis),
        connected_modules=_build_connected_modules(analysis),
        date=today,
    )

    # Replace the single changelog entry with full history
    if existing_changelog:
        changelog_section = "## 📝 Change Log (Auto)\n" + "\n".join(changelog_entries)
        readme = re.sub(
            r"## 📝 Change Log \(Auto\)\n.*",
            changelog_section,
            readme,
            flags=re.DOTALL,
        )

    return _restore_manual_blocks(readme, manual_blocks)


def _claude_readme(analysis: dict, existing_content: str = "") -> str:
    if not shutil.which("claude"):
        return None

    manual_blocks = _extract_manual_blocks(existing_content)
    today = datetime.now().strftime("%Y-%m-%d")

    prompt = f"""You are a technical documentation writer for a 12-organ AI workspace called SuneelWorkSpace.

Generate a README.md for this folder based on the analysis below.

ANALYSIS JSON:
{json.dumps(analysis, indent=2)}

OUTPUT FORMAT (use exactly these sections with emoji headers):
# 📁 <Folder Name>
## 🧠 Purpose
## ⚙️ Responsibilities
## 🔗 System Role
## 📂 Contents
## 🔄 Dependencies
## 🧩 Interactions
## 📈 Current Capabilities
## ⚠️ Gaps & Weaknesses
## 🚀 Suggested Enhancements
## 🔗 Connected Modules
## 📝 Change Log (Auto)

Rules:
- Be concise and technical
- Reference the 12-organ architecture where relevant
- List actual file names from the analysis in Contents
- Do not invent capabilities not evident in the analysis
- Add "- {today}: README auto-generated" to Change Log

Output ONLY the markdown. No preamble or explanation."""

    try:
        result = subprocess.run(
            ["claude", "--print", prompt],
            capture_output=True,
            text=True,
            timeout=90,
            cwd=str(Path(__file__).parent.parent.parent.parent),
        )
        if result.returncode == 0 and result.stdout.strip():
            content = result.stdout.strip()
            return _restore_manual_blocks(content, manual_blocks)
    except Exception:
        pass
    return None


def generate_readme(analysis: dict, existing_content: str = "", use_claude: bool = True) -> str:
    if use_claude:
        result = _claude_readme(analysis, existing_content)
        if result:
            return result
    return _rule_based_readme(analysis, existing_content)


def update_readme_for_folder(folder_path: str, use_claude: bool = True) -> bool:
    path = Path(folder_path).resolve()
    if not path.is_dir():
        return False

    from hands.automation.readme.intelligence_engine import analyze_folder
    analysis = analyze_folder(str(path))
    if not analysis:
        return False

    readme_path = path / "README.md"
    existing = readme_path.read_text(errors="ignore") if readme_path.exists() else ""

    new_content = generate_readme(analysis, existing, use_claude=use_claude)
    readme_path.write_text(new_content, encoding="utf-8")
    return True


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("folder", help="Folder to generate README for")
    parser.add_argument("--no-claude", action="store_true")
    args = parser.parse_args()

    ok = update_readme_for_folder(args.folder, use_claude=not args.no_claude)
    print("✅ README updated" if ok else "❌ Failed")
    sys.exit(0 if ok else 1)
